### ISSUE TITLE
Tracking Issue for v0.8.0

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#462]
Hello!

Over the past month, we've all been working away on v0.8.0 of the repository. I'm making an issue here (and pinning it) so people can see what work has been done, what work is ongoing, and what work might be useful to do. I will try, in the followup comments, to provide some direction on issues. We're also planning on having some breaking changes in the next few releases (and obviously the possibility of more after, but these next two are gonna be larger).

## Work Done

1. Added permissive dropping to the library, and restructured drop tokens in general to have a lifetime but not be as punishing to misuse. Now, instead of panicking when a token (such a "TabBarToken") is dropped without running `.end` on it, we'll just run `.end` in the drop code if necessary (if you manually call .end, that simply drops the token early), invoking the drop code. This will produce significant breaking changes, but they should be trivial to fix. This change was merged <https://github.com/imgui-rs/imgui-rs/pull/440>
2. Add `DrawList::add_image` and other functions. Allows for the draw image in the draw list functions to be used. Thank you @dbr for that! This is going to be very nice for *me* in particular :)) (I use a tilemap editor with your drawlist functions, and add image will be very nice!). This PR landed here https://github.com/imgui-rs/imgui-rs/pull/445
3. Added `_with_x` variants for most functions which take default arguments in C++. So for example, `same_line` previously took a float, but now `same_line` takes no parameters, but `same_line_with_pos` has been added. This should make `same_line` and `button` significantly less annoying to use. This was PRed here: https://github.com/imgui-rs/imgui-rs/pull/452
4. A few smaller commits: we added doc aliases to all of the functions for their original imgui counterparts, which should make finding imgui-rs equivalents to the imgui_demo.cpp file a lot easier. Thanks a lot @toyboot4e . Additionally, we added some input hinting for the input_text module (more on that below). thanks for that @lwiklendt. And finally, @dbr once again being excellent, upgraded to imgui v1.81, which was a smaller release than v1.80.

## Work in Progress:
1. Removal of ImStr from the library. Well, not quite removal. But a serious reduction in its usage. This PR is still in progress, but will introduce a trait, tentatively called `AsStr` (users won't interact with it much directly, but the name is very much in the air still!). Instead of taking `&ImStr`, most of the API will take `impl imgui::AsStr`, which will be implemented for `&str`. Nicely though, `format_args!` will be usable here too, which can enable a lot of string transfers to be non-allocating, even if they have to format. Internally, this is implementated by effectively just giving a SmallVec to the Ui where it stages strings under a certain size before handing it off to imgui, which then memcopy's that.
A long term goal of this project is to switch to the `string_view` branch of imgui, at least as a branch, and to give feedback on it.
If you have opinions on this change and its implementation, please leave comments here! https://github.com/imgui-rs/imgui-rs/pull/461

## Work That'd be Good to Get Done this Release (but not necessary)

- [ ] The tables API was stabilized in imgui v1.80, which we switched to in v0.7.0, but we don't have any API support for it yet. It would be excellent if someone could take a crack at wrapping over it. It doesn't look too bad, but you'll have to extensively use the token methods which were added above.
- [ ] The `input_x` widgets need some love. Right now, there's hilariously no way to set up a callback of various kinds as a user, except you CAN *ask* for them. This seems like a complex job, but look to the drag_drop.rs for how we ferry user code and types to imgui and back.
- [x] Fix our backends. Right now, we support gfx-rs. This has long been deprecated. We should replace that with a modern opengl library, probably `glow`. Additionally, supporting `sdl2` would be excellent, as that and `winit` are the largest rust windowing libs in use rn.
- [ ] More documentation. We're gradually gearing up to make a `docs/` folder, both for developing this repo and for users, which we'd like to expand. imgui_demo.cpp is still the best way to learn about imgui, and I doublt that'll change anytime soon, but there are a lot of "weird" areas of the API that would be excellent to have a place to direct users to. Moreover, for those users who are C++ averse, it would be nice to explain how ImGui's architecture (how renderers and backend come into play) works in a centralized location.

## Longer Term Work
1. Make everything build off of Ui. Right now, many structures must be imported into imgui, like `imgui::Window`, but this is weirdly annoying as a user. We're interested in switching back to primarily having all structs be built off of the `Ui` struct, which will make the API similar to the Dear ImGui C++.
2.  Yes, the docking branch. Our long term goals are to have SOME support for the docking_branch, and the string_view branch. What form that will take isn't clear yet.
3. Explore simplifying Ui. Right now it uses a lifetime and lots of state management and assertions. It weirdly doesn't use simplistic features, like reference counting, for most of its actions. It seems like it easily could.

Okay, that's probably the majority of what's planned or discussed right now. Obviously, there's a lot going on.

If anyone would liek to claim one of the three tasks still up for grabs, that would be **excellent**. Please leave a comment claiming the issue! Also if you want to kvetch about any of these changes, this is the place to do it!

**Comment by bjadamson** [comment]
Wow I just went looking for `DrawList::add_image` today. Great work!

**Comment by bjadamson** [comment]
Quick follow up, I switched over to the latest master branch and I noticed that the tokens are still documented as must use, even though they seem to be allowed to drop implicitly.

![image](https://user-images.githubusercontent.com/1087837/110978292-09b14b80-8318-11eb-908d-7851ac34e77d.png)

Should I be leaving this kind of feedback on the master branch here?

**Comment by Hperigo** [comment]
hey @sanbox-irl that's a great plan!

good to hear that one of the long term plan is to make the api more similar to the C++ lib, it's indeed a bit confusing right now

I wrote a [glow backend](https://github.com/Hperigo/imgui-glow-renderer) and would love to help integrating it into this repo. It's missing a couple of features and in need of a review, but I think it's a good start. 

let me know how I can help on that front.

**Comment by toyboot4e** [comment]
Cool!

I'm sorry from aside.. but I suggest using one backend crate for supporting some combinations of backends (platform + renderer). Benefits:

1. For users:
1-1. `imgui::Context` creation [utilitiy](https://github.com/toyboot4e/imgui-backends-rs/blob/ea5788bf387ab8dece30b2cf2456858be131521e/src/helper.rs#L21) (can be shared among backends).
1-2. [Backend](https://github.com/toyboot4e/imgui-backends-rs/blob/ea5788bf387ab8dece30b2cf2456858be131521e/src/lib.rs#L82) struct would be easier to use. For example, user does't have to call `Renderer::prepare_frame` explicitly.
2. For implementators:
2-1. `render` function can be implemented using an [iterator](https://github.com/toyboot4e/imgui-backends-rs/blob/ea5788bf387ab8dece30b2cf2456858be131521e/src/helper.rs#L186) of draw calls ([example](https://github.com/toyboot4e/imgui-backends-rs/blob/ea5788bf387ab8dece30b2cf2456858be131521e/src/renderer/glow.rs#L106))

My crate has issues (e.g., the demo's `Menus inside a regular window` doesn't work well)

---

Note: Backends in the wild:

* [imgui-sdl2](https://github.com/michaelfairley/rust-imgui-sdl2)
* [imgui-wgpu-rs](https://github.com/Yatekii/imgui-wgpu-rs)

**Comment by matthewjberger** [comment]
Really looking forward to the docking branch becoming available! Thank you for putting some docking support on the menu for the next release. :)

**Comment by jmaargh** [comment]
Hey, just a heads-up, I just finished a `glow` renderer based on [the example provided with upstream imgui](https://github.com/ocornut/imgui/blob/fe245914114588f272b0924538fdd43f6c127a26/backends/imgui_impl_opengl3.cpp).

It started as a small task for my own curiosity, but ballooned into something pretty flexible and I believe is strictly more feature-filled than the upstream one. However, it's obviously a lot less tested than upstream (and probably is missing some early-GL and early-GLES support, I've only tested on modern hardware and drivers). Other than testing, the only thing that's missing right now is documentation.

Assuming you're amenable to it, I'll create a PR in the next couple of days and start filling in docs.

(also, @Hperigo , I hope I'm not treading on your toes here. Like I said, it started as a personal exercise and just sort of grew. I'd love to work with you on review and getting this merged)

**Comment by thomcc** [comment]
> Assuming you're amenable to it, I'll create a PR in the next couple of days and start filling in docs.

Yes, please do. I think we'd be happy to maintain it, and I've been planning on doing this for a while (but never got around to it since I ended up not using `glow` for my game).

**Comment by sanbox-irl** [comment]
Update:

Hello everyone! Been a bit, huh? Let me write down what's happened so there's some public record (and to encourage comments).

First, in meta, I am now the primary maintainer of imgui-rs. Thom is still a maintainer too, just has less time. I also did not have much time over the summer (new job, new city), but am making more time to keep up with the repo. I wouldn't expect any serious changes beyond what was outlined before.

Second, 0.8.0 is likely to be the biggest update imgui-rs has ever. Here's a quick list:
1. Reworked all the begin/end functions to work on permissive drop tokens.
2. Completed the DrawList api. Before we're done here, we need to allow for foreground and background and general draw lists to be held at once (there's an issue on that I believe)
3. Changed the majority of functions to have 'with_x' variants. These have been expanded gradually. In 0.9.0, we will tackle removing/wrapping many of the builder patterns, but for now, you can finally just write 'ui.button("click me")' without jumping through the hoops of specifying size.
4. Might have noticed there the biggest change of this update -- the removal of ImStr and ImString from the API. In the next couple of days, I'll publish my branch which has made this change -- right now, it has replaced virtually everything with 'impl AsRef<str>'. Internally, we just keep a big buf of u8s and use it as a scratch buffer to give to imgui (if you've noticed some imgui methods requiring a Ui arg for which the param is just '_', well those now are real and doing work!). This trait may change to be more complex to allow for non-double copy work (ie, some trait over Fmt::Arguments so you can format_args! Things, though I'm not super convinced as to the use of this, and am unsure if we should have it at all).
5. The Input Callbacks have finally been added to the library. They are mostly advanced usages that users don't really need (it seems almost no one has noticed that we don't support them!) but they're there now.
6. The new Tables API will be wrapped. It may or may not involve a jump in MSRV (I used some const generics), but they could just be cfged around. There is a PR for this where you can see my current work.
7. We have a new rendering backend! We now have a 'glow' implementation. Unfortunately, we're stuck on 0.10, and now 0.11, but ideally, the roadblock around that will be solved before 0.8 is released.
8. A bunch of smaller changes too! Too many to even list really, but notably the imgui freetype feature has been added, which makes small typeface look better

One minor issue right now is a conflict in the examples around a glium version. If you run cargo update, it seems to fix itself, but if anyone knows how to sort that out themselves, that'd be very appreciated!

Ok, that's a lot -- if anyone has any thoughts feel free to write them out

**Comment by sanbox-irl** [comment]
Okay, everything in the above list is done with the exception of getting the new `glow` backend on current glow. talking with the maintainers of glow on how to make this work. 

Either way though, I am planning on hitting the publish button on all this on Thursday, Sept 16, so please all let me know if you see any huge errors or corrections that should be made before then!

**Comment by sanbox-irl** [comment]
remembering to do this final comment here before release -- https://github.com/imgui-rs/imgui-rs/pull/519

**Comment by sanbox-irl** [comment]
I decided to feature gate the `tables-api` for two reasons:

1. It is marked as "Beta". Although I think that its API is quite stable and won't really change, that is a factor to consider.
2. It currently can cause a segfault in two functions. (I was dumb and trigger that segfault at work the other day). That segfault is just a null deref caused by using the tables api without using `begin_table` (or in my case, using the tables api within a child window inside a table, but before ending the child window). It produces an ugly crash (ie, no stacktrace).
3. We can't yet check if we are *in* a table currently, which prevents us from writing some debug assertions in Rust to wrap around #2. Therefore, we're somewhat stuck in being forced to allow users to segfault through safe code.

If any of these three conditions change, I will remove the feature gate (none of them are strong enough on their own, but collectively, I think it's the right call).

**Comment by sanbox-irl** [comment]
Closing, as 0.8.0 has been released 🎉

**Comment by thomcc** [comment]
I think the segfault is strong enough on its own. I'd also suggest that it should be more than debug_assert when a check is available.
